version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment: 
      pip install --no-deps git+https://github.com/griffithlab/sphinxcontrib-programoutput.git#egg=sphinxcontrib-programoutput

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
